name: kasir
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

  # UI
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.17.5
  file_picker: ^8.0.7
  firebase_storage: ^11.7.7
  mime: ^2.0.0
  image_picker: ^1.2.0
  flutter_image_compress: ^2.3.0
  intl: ^0.20.2
   

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/lapangan1.jpg
    - assets/images/lapangan2.jpg
    - assets/images/lapangan3.jpg
