name: kasir
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

  # UI
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  supabase_flutter: ^2.10.1
  flutter_image_compress: ^2.3.0
  image_picker: ^1.2.0
  file_picker: ^8.0.7
  printing: ^5.13.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  
   

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
   